from .BaseAgent import *
from .VanillaDQN import *
from .DQN import *
from .DDQN import *
from .MaxminDQN import *
from .AlterDQN import *
from .SoftAlterDQN import *
from .AveragedDQN import *
from .WDQN import *
from .SCDQN import *
from .SoftmaxDQN import *
from .EBDQN import *
from .REDQN import *
from .AdaEDQN import *